[phases.setup]
nixPkgs = ["php82Extensions.mbstring", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.curl", "php82Extensions.gd", "php82Extensions.zip", "php82Extensions.dom", "php82Extensions.xml", "nodejs-18_x"]

[phases.install]
cmds = [
    "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer",
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm ci"
]

[phases.build]
cmds = [
    "npm run build",
    "mkdir -p storage/logs storage/framework/cache storage/framework/sessions storage/framework/views bootstrap/cache",
    "chmod -R 775 storage bootstrap/cache",
    "chmod +x start.sh"
]

[start]
cmd = "./start.sh"
